import Header from "@/components/Header";
import Footer from "@/components/Footer";
import { useEffect } from "react";

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: `By accessing or using any Autonex AI product, platform, or service (collectively, "Services"), you agree to be bound by these Terms of Service ("Terms"). If you are entering into these Terms on behalf of a company or other legal entity, you represent that you have the authority to bind that entity. If you do not agree to these Terms, you may not use the Services.`,
  },
  {
    title: "2. Description of Services",
    content: `Autonex AI provides industrial intelligence software products including but not limited to: V.I.G.I.L (Visual Intelligence & Guard Inspection Layer), WIL (Warehouse Intelligence & Logistics), Digital Twin simulation platform, and AI ERP / eBMR (Electronic Batch Manufacturing Records). These products are deployed on-premise or via secure cloud infrastructure and are designed for use in manufacturing, warehousing, and industrial environments.`,
  },
  {
    title: "3. Licence Grant",
    content: `Subject to these Terms and payment of applicable fees, Autonex AI grants you a limited, non-exclusive, non-transferable, revocable licence to access and use the Services solely for your internal business operations. You may not sublicence, resell, or otherwise transfer your rights under this licence without prior written consent from Autonex AI.`,
  },
  {
    title: "4. Permitted Use",
    content: `You agree to use the Services only for lawful purposes and in accordance with these Terms. You shall not: (a) reverse engineer, decompile, or disassemble any software component of the Services; (b) attempt to gain unauthorised access to any system, network, or data; (c) use the Services to process data in violation of applicable privacy laws; (d) reproduce, duplicate, copy, or sell any portion of the Services without express written permission; or (e) use the Services in any manner that could damage, disable, or impair the Services.`,
  },
  {
    title: "5. Data and Privacy",
    content: `Autonex AI processes video feeds, sensor data, production telemetry, and other operational data to deliver its Services. You retain ownership of all data generated by your operations. Autonex AI processes this data solely to provide and improve the Services as outlined in our Privacy Policy. Camera feeds and production data are processed locally where possible and are not stored on Autonex AI servers beyond the retention period agreed in your service agreement.`,
  },
  {
    title: "6. Intellectual Property",
    content: `The Services, including all software, algorithms, models, patents (including the Digital Twin simulation patent published at IIT Bombay), documentation, and related materials, are and remain the exclusive intellectual property of Autonex AI and its licensors. Nothing in these Terms grants you any ownership rights in the Services. Any feedback, suggestions, or improvements you provide may be used by Autonex AI without restriction or compensation.`,
  },
  {
    title: "7. Confidentiality",
    content: `Each party agrees to keep confidential any non-public information disclosed by the other party in connection with the Services ("Confidential Information"). Confidential Information does not include information that: (a) is or becomes publicly known through no breach of this agreement; (b) was rightfully known before disclosure; (c) is independently developed without use of the other party's Confidential Information; or (d) is required to be disclosed by law or court order.`,
  },
  {
    title: "8. Service Availability and Uptime",
    content: `Autonex AI will use commercially reasonable efforts to maintain Services availability. Scheduled maintenance windows will be communicated with at least 48 hours notice where possible. Autonex AI does not guarantee uninterrupted, error-free operation and shall not be liable for downtime caused by circumstances beyond its reasonable control, including but not limited to network failures, hardware issues, or force majeure events.`,
  },
  {
    title: "9. Fees and Payment",
    content: `Fees for the Services are as specified in your applicable order form or service agreement. All fees are exclusive of applicable taxes. Payment is due within 30 days of invoice unless otherwise agreed. Late payments may accrue interest at 1.5% per month or the maximum rate permitted by applicable law, whichever is lower. Autonex AI reserves the right to suspend Services for overdue accounts after reasonable notice.`,
  },
  {
    title: "10. Limitation of Liability",
    content: `To the maximum extent permitted by applicable law, Autonex AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of profits, revenue, data, or goodwill, even if Autonex AI has been advised of the possibility of such damages. Autonex AI's total cumulative liability arising out of or relating to these Terms shall not exceed the total fees paid by you in the twelve (12) months preceding the claim.`,
  },
  {
    title: "11. Indemnification",
    content: `You agree to indemnify, defend, and hold harmless Autonex AI and its officers, directors, employees, and agents from and against any claims, damages, losses, costs, and expenses (including reasonable legal fees) arising out of: (a) your use of the Services in violation of these Terms; (b) your violation of any applicable law or regulation; or (c) your infringement of any third-party intellectual property or privacy rights.`,
  },
  {
    title: "12. Termination",
    content: `Either party may terminate these Terms upon written notice if the other party materially breaches these Terms and fails to cure such breach within 30 days of written notice. Autonex AI may immediately suspend or terminate your access to the Services if you violate Sections 4 or 6 of these Terms. Upon termination, all licences granted herein shall cease and you must destroy or return all Confidential Information.`,
  },
  {
    title: "13. Governing Law",
    content: `These Terms are governed by and construed in accordance with the laws of India, without regard to its conflict of law principles. Any dispute arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in Mumbai, Maharashtra, India.`,
  },
  {
    title: "14. Changes to Terms",
    content: `Autonex AI reserves the right to modify these Terms at any time. We will provide notice of material changes by posting the updated Terms on our website or by email. Your continued use of the Services after the effective date of any changes constitutes your acceptance of the revised Terms.`,
  },
  {
    title: "15. Contact",
    content: `If you have any questions about these Terms, please contact us at:\n\nAutonex AI\nEmail: legal@autonexai360.com\nWebsite: www.autonexai360.com`,
  },
];

export default function TermsOfService() {
  useEffect(() => {
    window.scrollTo({ top: 0, behavior: "smooth" });
  }, []);

  return (
    <div style={{ background: "var(--background, #060d1f)", minHeight: "100vh" }}>
      <Header />

      {/* Hero */}
      <section
        className="relative pt-40 pb-16 text-center px-4 overflow-hidden"
        style={{ background: "linear-gradient(180deg, rgba(22,55,145,0.12) 0%, transparent 100%)" }}
      >
        {/* Glow */}
        <div
          className="absolute pointer-events-none"
          style={{
            top: 0, left: "50%", transform: "translateX(-50%)",
            width: "60%", height: 320,
            background: "radial-gradient(ellipse at 50% 0%, rgba(98,170,222,0.14) 0%, transparent 70%)",
            filter: "blur(40px)",
          }}
        />
        <div className="relative z-10 max-w-3xl mx-auto">
          <div
            className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full mb-6 text-xs font-semibold tracking-widest uppercase"
            style={{ background: "rgba(98,170,222,0.1)", border: "1px solid rgba(98,170,222,0.25)", color: "#62AADE" }}
          >
            Legal
          </div>
          <h1
            className="text-4xl sm:text-5xl md:text-6xl font-black text-white leading-tight mb-5"
            style={{ letterSpacing: "-0.025em" }}
          >
            Terms of Service
          </h1>
          <p className="text-base text-white/50 max-w-xl mx-auto">
            Last updated: May 2025 &nbsp;·&nbsp; Effective immediately
          </p>
        </div>
      </section>

      {/* Content */}
      <section className="max-w-3xl mx-auto px-6 pb-32">
        {/* Intro */}
        <div
          className="rounded-2xl p-6 mb-10"
          style={{ background: "rgba(98,170,222,0.06)", border: "1px solid rgba(98,170,222,0.15)" }}
        >
          <p className="text-white/70 text-sm leading-relaxed">
            Please read these Terms of Service carefully before using Autonex AI's products and services.
            These Terms constitute a legally binding agreement between you and Autonex AI Pvt. Ltd.
            ("Autonex AI", "we", "us", or "our").
          </p>
        </div>

        {/* Sections */}
        <div className="space-y-10">
          {sections.map((s, i) => (
            <div key={i}>
              <h2
                className="text-lg font-black text-white mb-3"
                style={{ letterSpacing: "-0.01em" }}
              >
                {s.title}
              </h2>
              <div
                className="h-px mb-4"
                style={{ background: "linear-gradient(to right, rgba(98,170,222,0.3), transparent)" }}
              />
              <p className="text-white/60 text-[14px] leading-relaxed whitespace-pre-line">
                {s.content}
              </p>
            </div>
          ))}
        </div>
      </section>

      <Footer hideCta />
    </div>
  );
}
